### ISSUE TITLE
Unable to creaete new sermon

### ISSUE THREAD

**Issue by brendan-pike** [Bakual/SermonSpeaker#124]
After upgrading to Joomla 5.1.0 and SermonSpeaker 6.1.6 I now get this error when trying to create a sermon.

` There is no "com_sermonspeaker.id3-lookup" asset of a "script" type in the registry. `

**Comment by Bakual** [comment]
Sorry, I just saw this issue now. Did you get this resolved in the meantime?
Otherwise I would suggest to install SermonSpeaker over the existing installation. Most issues are solved with that.

If that doesn't help, can I get you to post your issue in my support forum at https://www.sermonspeaker.net/forum/index.html?
